### ISSUE TITLE
Getting Errors

### ISSUE THREAD

**Issue by marcpope** [masipcat/beluga-lets-encrypt#1]
I am trying to run this on CentOS 7, with Python 2.7.5 and I get these errors:

Traceback (most recent call last):
  File "renew.py", line 43, in <module>
    main()
  File "renew.py", line 40, in main
    renew_certs(config)
  File "renew.py", line 18, in renew_certs
    response = run_beluga(config, ['--path', 'ssl-certificates'])
  File "renew.py", line 13, in run_beluga
    output = subprocess.check_output(['beluga'] + auth_args + other_args)
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by masipcat** [comment]
I haven't used this script for a while and I almost remeber nothing... but I think that you need to install this command line tool https://github.com/belugacdn/python-beluga as well.
